spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:13306/mobruji?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:mobruji}
    password: ${MYSQL_PASSWORD:mobruji}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
